import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const pw = ['/Users/matteozoccolan/.npm/_npx/9833c18b2d85bc59/node_modules/playwright-core',
  '/Users/matteozoccolan/.npm/_npx/e41f203b7505f1fb/node_modules/playwright-core'].find((p) => fs.existsSync(path.join(p, 'index.js')));
const { chromium } = require(pw);
const EXE = '/Users/matteozoccolan/Library/Caches/ms-playwright/chromium_headless_shell-1217/chrome-headless-shell-mac-arm64/chrome-headless-shell';
const b = await chromium.launch({ executablePath: EXE });
const p = await (await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 })).newPage();
await p.goto('http://localhost:3000/v2/preview', { waitUntil: 'networkidle' });
const hasIco = await p.$('.icoBtn') !== null;
const before = await p.evaluate(() => document.querySelector('.keiko').className);
await p.click('.icoBtn');
await p.waitForTimeout(400);
const after = await p.evaluate(() => document.querySelector('.keiko').className);
await p.click('.icoBtn');
await p.waitForTimeout(400);
const after2 = await p.evaluate(() => document.querySelector('.keiko').className);
console.log(JSON.stringify({ hasIco, before, after1click: after, after2click: after2 }, null, 2));
await b.close();
